FROM ubuntu:14.04

# Install ssh
#RUN echo 'Acquire::http { Proxy "http://192.168.1.100:3142"; };' > /etc/apt/apt.conf.d/proxy.conf
RUN apt-get update
RUN apt-get install -y openssh-server

# Setting ssh
RUN mkdir /var/run/sshd
RUN /usr/sbin/sshd
EXPOSE 22

# Creating user and setting its password
RUN echo root:pass | chpasswd

# Setting ssh login without password
RUN mkdir -p /root/.ssh
RUN chmod 700 /root/.ssh
ADD ./id_rsa.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys

# startup the sshd process
ADD init.sh /usr/bin/init.sh
CMD ["/usr/bin/init.sh"]
